"""empty message

Revision ID: 2f4acf022f35
Revises: 55ca12bbe4ef
Create Date: 2015-06-26 11:53:38.560942

"""

# revision identifiers, used by Alembic.
revision = '2f4acf022f35'
down_revision = '55ca12bbe4ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
