"""empty message

Revision ID: 38f1384fd753
Revises: 57e0aed3c20e
Create Date: 2015-06-16 22:18:54.801890

"""

# revision identifiers, used by Alembic.
revision = '38f1384fd753'
down_revision = '57e0aed3c20e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_link', sa.String(length=256), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('show_full_name', sa.Boolean(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_link')
    )
    op.create_index(op.f('ix_profiles_full_name'), 'profiles', ['full_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_full_name'), table_name='profiles')
    op.drop_table('profiles')
    ### end Alembic commands ###
