"""empty message

Revision ID: 50c06cd2981a
Revises: 2f4acf022f35
Create Date: 2015-06-26 18:10:54.902972

"""

# revision identifiers, used by Alembic.
revision = '50c06cd2981a'
down_revision = '2f4acf022f35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'timestamp')
    ### end Alembic commands ###
