"""empty message

Revision ID: 51aefaea0981
Revises: None
Create Date: 2015-07-06 01:24:34.709029

"""

# revision identifiers, used by Alembic.
revision = '51aefaea0981'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
