"""empty message

Revision ID: 55ca12bbe4ef
Revises: None
Create Date: 2015-06-26 11:34:03.227819

"""

# revision identifiers, used by Alembic.
revision = '55ca12bbe4ef'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
