"""empty message

Revision ID: 57e0aed3c20e
Revises: None
Create Date: 2015-06-16 22:04:28.536366

"""

# revision identifiers, used by Alembic.
revision = '57e0aed3c20e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
